"""Aggregate hypothesis cross-validation results into stats, paired tests, LaTeX tables, and publication-ready boxplots.

Supports H1, H2, H3, H4, and generic fold results generated by the training pipeline.

Features:
  - Formal, readable label mapping for thesis and paper publication.
  - Paired parametric (paired t-test, Cohen's d) and non-parametric (Wilcoxon signed-rank) hypothesis testing.
  - High-resolution (300 DPI) raster PNG and vector PDF boxplots with jittered fold points and statistical annotations.
  - Multi-format exports: CSV, Markdown report, and LaTeX table snippets.

Examples:
    python scripts/analysis/aggregate_hypothesis.py \\
        --fold-results ../results_from_apl19/h1_effb0_32fold_8gpu/fold_results.csv \\
        --hypothesis h1 \\
        --output-dir results/h1_effb0_32fold

    python scripts/analysis/aggregate_hypothesis.py \\
        --fold-results ../results_from_apl19/h4_effb0_reuseSmall_res34_trainLarge_32fold_8gpu/fold_results.csv \\
        --configs-dir ../results_from_apl19/h4_effb0_reuseSmall_res34_trainLarge_32fold_8gpu/configs \\
        --hypothesis h4 \\
        --output-dir results/h4_backbones
"""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
from scipy import stats as sstats

from common import ROOT, load_yaml, resolve_path

# Standard formal display names for experiment arms across hypotheses
DEFAULT_LABEL_MAP: Dict[str, str] = {
    "baseline_single_phase": "Single-Phase Baseline (PV)",
    "multiphase_train_single_infer": "Multiphase Training (PV Eval)",
    "baseline_unregistered": "Unregistered Baseline",
    "registered_training": "Registered Data",
    "small_single_phase": "EfficientNet-B0 (Single-Phase)",
    "small_multiphase": "EfficientNet-B0 (Multiphase)",
    "large_single_phase": "ResNet-34 (Single-Phase)",
    "large_multiphase": "ResNet-34 (Multiphase)",
    "resnet34_single_phase": "ResNet-34 (Single-Phase)",
    "resnet34_multiphase": "ResNet-34 (Multiphase)",
    "efficientnet_b0_single_phase": "EfficientNet-B0 (Single-Phase)",
    "efficientnet_b0_multiphase": "EfficientNet-B0 (Multiphase)",
}

# Color palette for distinct arms (academic, colorblind-friendly accents)
ARM_COLORS: List[str] = [
    "#4A90E2",  # Soft Navy Blue (e.g. Baseline)
    "#2ECC71",  # Emerald Green (e.g. Multiphase)
    "#E67E22",  # Warm Amber / Orange (e.g. Unregistered)
    "#9B59B6",  # Amethyst Purple (e.g. Large Multiphase)
    "#1ABC9C",  # Dark Turquoise
    "#E74C3C",  # Crimson Coral
]

CAUTION_NOTE = (
    "Methodological Note: Folds are derived from k-fold cross-validation splits. Because training sets "
    "overlap across folds, statistical test p-values and confidence intervals reflect within-dataset "
    "comparative variance across partitions rather than fully independent patient cohort replications."
)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument(
        "--fold-results",
        type=str,
        required=True,
        help="Path to fold_results.csv or folder containing fold_results.csv.",
    )
    p.add_argument(
        "--hypothesis",
        type=str,
        default="auto",
        choices=["auto", "h1", "h2", "h3", "h4", "custom"],
        help="Hypothesis preset for automated pairing, ordering, and titles.",
    )
    p.add_argument(
        "--configs-dir",
        type=str,
        default=None,
        help="Optional directory containing arm yaml configs to resolve encoder backbones.",
    )
    p.add_argument(
        "--pairs",
        type=str,
        action="append",
        default=[],
        help="arm_a:arm_b comparison pair (repeatable). Statistics computed as (b - a).",
    )
    p.add_argument(
        "--label-map",
        type=str,
        default=None,
        help="Custom label mapping as 'arm_key=Formal Label,arm_key2=Label 2' or json string.",
    )
    p.add_argument("--dice-column", type=str, default="best_val_dice", help="Column name containing Dice scores.")
    p.add_argument("--order", type=str, nargs="+", default=None, help="Explicit display order for arms.")
    p.add_argument("--title", type=str, default=None, help="Custom title for plots and reports.")
    p.add_argument("--output-dir", type=str, required=True, help="Target directory for output files.")
    p.add_argument(
        "--copy-to-thesis-img",
        type=str,
        default=None,
        help="Optional destination path (e.g. Masters_Thesis/img/h1_boxplot.png) to copy the generated figure.",
    )
    p.add_argument("--dpi", type=int, default=300, help="DPI for raster plot output (default: 300).")
    return p.parse_args()


def _infer_hypothesis_preset(path_str: str, explicit: str) -> str:
    if explicit != "auto":
        return explicit.lower()
    lower = path_str.lower()
    for h in ["h1", "h2", "h3", "h4"]:
        if h in lower:
            return h
    return "custom"


def _parse_custom_label_map(label_map_arg: Optional[str]) -> Dict[str, str]:
    if not label_map_arg:
        return {}
    raw = label_map_arg.strip()
    if raw.startswith("{") and raw.endswith("}"):
        try:
            return json.loads(raw)
        except Exception:
            pass
    mapping = {}
    for item in raw.split(","):
        item = item.strip()
        if "=" in item:
            k, v = item.split("=", 1)
            mapping[k.strip()] = v.strip()
        elif ":" in item:
            k, v = item.split(":", 1)
            mapping[k.strip()] = v.strip()
    return mapping


def _resolve_arm_label(
    arm: str,
    configs_dir: Optional[Path],
    custom_map: Dict[str, str],
) -> str:
    if arm in custom_map:
        return custom_map[arm]

    if arm in ["baseline_single_phase", "multiphase_train_single_infer", "baseline_unregistered", "registered_training"]:
        return DEFAULT_LABEL_MAP[arm]

    if configs_dir is not None:
        cfg_path = configs_dir / f"{arm}.yaml"
        if cfg_path.exists():
            cfg = load_yaml(cfg_path)
            backbone = str(cfg.get("model", {}).get("encoder_backbone", "")).strip()
            is_multiphase = cfg.get("data", {}).get("force_phase_input") is None
            regime = "Multiphase" if is_multiphase else "Single-Phase"
            backbone_name = {
                "resnet34": "ResNet-34",
                "efficientnet_b0": "EfficientNet-B0",
                "efficientnet-b0": "EfficientNet-B0",
            }.get(backbone.lower(), backbone.capitalize())
            return f"{backbone_name} ({regime})"

    if arm in DEFAULT_LABEL_MAP:
        return DEFAULT_LABEL_MAP[arm]

    clean = arm.replace("_", " ").title()
    return clean


def _compute_descriptive_stats(df: pd.DataFrame, dice_col: str) -> pd.DataFrame:
    rows = []
    for arm, group in df.groupby("arm", sort=False):
        label = group["label"].iloc[0]
        vals = group[dice_col].dropna().to_numpy(dtype=np.float64)
        n = len(vals)
        mean_val = float(np.mean(vals))
        std_val = float(np.std(vals, ddof=1)) if n > 1 else 0.0
        se_val = std_val / np.sqrt(n) if n > 1 else 0.0
        median_val = float(np.median(vals))
        q25 = float(np.percentile(vals, 25))
        q75 = float(np.percentile(vals, 75))
        iqr = q75 - q25
        min_val = float(np.min(vals))
        max_val = float(np.max(vals))
        t_crit = sstats.t.ppf(0.975, n - 1) if n > 1 else 1.96
        ci_low = mean_val - t_crit * se_val
        ci_high = mean_val + t_crit * se_val

        rows.append(
            {
                "arm": arm,
                "label": label,
                "n_folds": n,
                "mean": mean_val,
                "std": std_val,
                "sem": se_val,
                "ci95_low": ci_low,
                "ci95_high": ci_high,
                "median": median_val,
                "q25": q25,
                "q75": q75,
                "iqr": iqr,
                "min": min_val,
                "max": max_val,
            }
        )
    return pd.DataFrame(rows)


def _compute_paired_stats(
    df: pd.DataFrame,
    arm_a: str,
    arm_b: str,
    label_a: str,
    label_b: str,
    dice_col: str,
) -> Dict[str, Any]:
    sub_a = df.loc[df["arm"] == arm_a].set_index("fold")[dice_col]
    sub_b = df.loc[df["arm"] == arm_b].set_index("fold")[dice_col]
    joined = pd.concat([sub_a, sub_b], axis=1, keys=["a", "b"]).dropna()
    diff = joined["b"] - joined["a"]
    n = len(diff)
    if n < 2:
        return {"arm_a": arm_a, "arm_b": arm_b, "label_a": label_a, "label_b": label_b, "n_folds": n, "note": "Insufficient paired folds"}

    mean_a = float(joined["a"].mean())
    mean_b = float(joined["b"].mean())
    std_a = float(joined["a"].std(ddof=1))
    std_b = float(joined["b"].std(ddof=1))
    mean_diff = float(diff.mean())
    std_diff = float(diff.std(ddof=1))
    se_diff = std_diff / np.sqrt(n)
    t_crit = sstats.t.ppf(0.975, n - 1)
    ci95_low = mean_diff - t_crit * se_diff
    ci95_high = mean_diff + t_crit * se_diff

    # Cohen's d for paired samples
    cohen_d = mean_diff / std_diff if std_diff > 0 else 0.0

    t_stat, p_t = sstats.ttest_rel(joined["b"], joined["a"])
    try:
        w_res = sstats.wilcoxon(joined["b"], joined["a"])
        w_stat, p_w = float(w_res.statistic), float(w_res.pvalue)
    except Exception:
        w_stat, p_w = float("nan"), float("nan")

    wins_b = int((diff > 0).sum())
    ties = int((diff == 0).sum())
    losses_b = int((diff < 0).sum())

    return {
        "arm_a": arm_a,
        "arm_b": arm_b,
        "label_a": label_a,
        "label_b": label_b,
        "comparison": f"{label_b} vs {label_a}",
        "n_folds": n,
        "mean_a": mean_a,
        "std_a": std_a,
        "mean_b": mean_b,
        "std_b": std_b,
        "mean_diff": mean_diff,
        "std_diff": std_diff,
        "sem_diff": se_diff,
        "ci95_low": ci95_low,
        "ci95_high": ci95_high,
        "cohens_d": cohen_d,
        "wins_b": wins_b,
        "ties": ties,
        "losses_b": losses_b,
        "win_rate_b": wins_b / n * 100.0,
        "t_statistic": float(t_stat),
        "paired_ttest_p": float(p_t),
        "wilcoxon_stat": w_stat,
        "wilcoxon_p": p_w,
    }


def _plot_formal_boxplot(
    df: pd.DataFrame,
    dice_col: str,
    ordered_arms: List[str],
    arm_labels: List[str],
    title: str,
    output_png: Path,
    output_pdf: Path,
    paired_results: List[Dict[str, Any]],
    dpi: int = 300,
) -> None:
    import matplotlib.pyplot as plt
    import matplotlib.ticker as ticker

    # Professional styling settings
    plt.rcParams.update(
        {
            "font.family": "sans-serif",
            "font.sans-serif": ["Arial", "DejaVu Sans", "Helvetica"],
            "axes.edgecolor": "#2C3E50",
            "axes.linewidth": 1.1,
            "xtick.major.size": 5,
            "ytick.major.size": 5,
        }
    )

    n_arms = len(ordered_arms)
    fig_width = max(7.0, 3.2 * n_arms)
    fig_height = 6.2
    fig, ax = plt.subplots(figsize=(fig_width, fig_height), dpi=dpi)

    rng = np.random.default_rng(42)
    values_per_arm = [
        df.loc[df["arm"] == arm, dice_col].to_numpy(dtype=np.float64)
        for arm in ordered_arms
    ]

    positions = np.arange(1, n_arms + 1)
    colors = [ARM_COLORS[i % len(ARM_COLORS)] for i in range(n_arms)]

    box_plot = ax.boxplot(
        values_per_arm,
        positions=positions,
        widths=0.48,
        showmeans=True,
        patch_artist=True,
        medianprops={"color": "#111111", "linewidth": 2.2},
        meanprops={
            "marker": "D",
            "markerfacecolor": "#FFFFFF",
            "markeredgecolor": "#111111",
            "markersize": 7.0,
            "markeredgewidth": 1.5,
        },
        whiskerprops={"color": "#2C3E50", "linewidth": 1.3},
        capprops={"color": "#2C3E50", "linewidth": 1.3},
        flierprops={
            "marker": "o",
            "markerfacecolor": "#95A5A6",
            "markeredgecolor": "#2C3E50",
            "markersize": 4,
            "alpha": 0.5,
        },
    )

    for patch, col in zip(box_plot["boxes"], colors):
        patch.set_facecolor(col)
        patch.set_alpha(0.70)
        patch.set_edgecolor("#1A252F")
        patch.set_linewidth(1.4)

    # Jittered fold points for complete distribution transparency
    for idx, (ys, col) in enumerate(zip(values_per_arm, colors), start=1):
        xs = np.full(len(ys), idx, dtype=np.float64) + rng.uniform(-0.11, 0.11, size=len(ys))
        ax.scatter(
            xs,
            ys,
            s=42,
            alpha=0.85,
            color=col,
            edgecolors="#1A252F",
            linewidths=0.7,
            zorder=4,
        )

    all_y = np.concatenate(values_per_arm) if len(values_per_arm) > 0 else np.array([0.0])
    y_min, y_max = float(all_y.min()), float(all_y.max())
    y_pad = (y_max - y_min) * 0.12 if y_max > y_min else 0.05
    lower_bound = max(0.0, y_min - y_pad)
    upper_bound = min(1.0, y_max + y_pad * 1.6)

    # Statistical annotation if paired comparisons exist
    if paired_results and len(ordered_arms) == 2:
        pair = paired_results[0]
        mean_diff = pair.get("mean_diff", 0.0)
        p_val = pair.get("paired_ttest_p", 1.0)
        p_text = f"p = {p_val:.3f}" if p_val >= 0.001 else "p < 0.001"
        signif = " (N.S.)" if p_val >= 0.05 else (" (*)" if p_val < 0.05 and p_val >= 0.01 else " (**)")
        stat_label = f"$\\Delta$ Dice = {mean_diff:+.4f} ({p_text}{signif})\n95% CI: [{pair.get('ci95_low', 0):+.4f}, {pair.get('ci95_high', 0):+.4f}]"

        x1, x2 = 1, 2
        bracket_y = y_max + y_pad * 0.4
        bracket_h = y_pad * 0.15
        ax.plot([x1, x1, x2, x2], [bracket_y, bracket_y + bracket_h, bracket_y + bracket_h, bracket_y], lw=1.2, c="#2C3E50")
        ax.text(
            (x1 + x2) * 0.5,
            bracket_y + bracket_h + y_pad * 0.08,
            stat_label,
            ha="center",
            va="bottom",
            fontsize=9.5,
            fontweight="semibold",
            color="#2C3E50",
            bbox=dict(boxstyle="round,pad=0.35", facecolor="#F8F9F9", edgecolor="#BDC3C7", alpha=0.95),
        )
        upper_bound = max(upper_bound, bracket_y + bracket_h + y_pad * 1.1)

    # Sub-text with Mean and Median per arm
    for idx, (arm, label, ys) in enumerate(zip(ordered_arms, arm_labels, values_per_arm), start=1):
        m = float(np.mean(ys))
        s = float(np.std(ys, ddof=1))
        med = float(np.median(ys))
        txt = f"Mean: {m:.4f} \u00b1 {s:.4f}\nMedian: {med:.4f}"
        ax.text(
            idx,
            lower_bound + (y_pad * 0.1),
            txt,
            ha="center",
            va="bottom",
            fontsize=9.0,
            color="#2C3E50",
            bbox=dict(boxstyle="square,pad=0.25", facecolor="#FFFFFF", edgecolor="#D5D8DC", alpha=0.9),
            zorder=5,
        )

    ax.set_xticks(positions)
    ax.set_xticklabels(arm_labels, fontsize=11.0, fontweight="bold", ha="center")
    ax.set_ylabel("Validation Dice Coefficient", fontsize=11.5, fontweight="bold", labelpad=8)
    ax.set_title(title, fontsize=12.5, fontweight="bold", pad=14, color="#1A252F")

    ax.set_ylim(lower_bound, upper_bound)
    ax.yaxis.set_major_formatter(ticker.FormatStrFormatter("%.2f"))
    ax.grid(axis="y", linestyle="--", alpha=0.45, color="#BDC3C7")
    ax.set_axisbelow(True)

    from matplotlib.lines import Line2D
    legend_elements = [
        Line2D([0], [0], color="#111111", lw=2.2, label="Median"),
        Line2D([0], [0], marker="D", color="w", markeredgecolor="#111111", markerfacecolor="#FFFFFF", markersize=7, label="Mean (\u00b1 SEM)"),
        Line2D([0], [0], marker="o", color="w", markeredgecolor="#1A252F", markerfacecolor="#4A90E2", markersize=6, label="Fold Observation (N=32)"),
    ]
    ax.legend(handles=legend_elements, loc="upper right", framealpha=0.95, fontsize=9.0, edgecolor="#D5D8DC")

    fig.tight_layout()
    output_png.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_png, dpi=dpi)
    fig.savefig(output_pdf)
    plt.close(fig)


def _generate_latex_table(stats_df: pd.DataFrame, paired_df: Optional[pd.DataFrame], caption: str, label: str) -> str:
    lines = [
        r"\begin{table}[htbp]",
        r"  \centering",
        f"  \\caption{{{caption}}}",
        f"  \\label{{{label}}}",
        r"  \begin{tabular}{lcccccc}",
        r"    \hline",
        r"    \textbf{Experimental Arm} & \textbf{Folds} & \textbf{Mean Dice} & \textbf{Std} & \textbf{95\% CI} & \textbf{Median} & \textbf{IQR} \\",
        r"    \hline",
    ]

    for _, row in stats_df.iterrows():
        name = str(row["label"]).replace("_", r"\_")
        n = int(row["n_folds"])
        mean = f"{row['mean']:.4f}"
        std = f"{row['std']:.4f}"
        ci = f"[{row['ci95_low']:.4f}, {row['ci95_high']:.4f}]"
        med = f"{row['median']:.4f}"
        iqr = f"{row['iqr']:.4f}"
        lines.append(f"    {name} & {n} & {mean} & {std} & {ci} & {med} & {iqr} \\\\")

    lines.extend([
        r"    \hline",
        r"  \end{tabular}",
    ])

    if paired_df is not None and not paired_df.empty:
        lines.extend([
            r"  \vspace{0.3cm}",
            r"  \begin{tabular}{lcccc}",
            r"    \hline",
            r"    \textbf{Paired Comparison} & \textbf{$\Delta$ Mean} & \textbf{95\% CI ($\Delta$)} & \textbf{Paired $t$-test $p$} & \textbf{Wilcoxon $p$} \\",
            r"    \hline",
        ])
        for _, prow in paired_df.iterrows():
            comp_name = str(prow.get("comparison", f"{prow['arm_b']} vs {prow['arm_a']}")).replace("_", r"\_")
            d_mean = f"{prow['mean_diff']:+.4f}"
            d_ci = f"[{prow['ci95_low']:+.4f}, {prow['ci95_high']:+.4f}]"
            p_t = f"{prow['paired_ttest_p']:.4f}" if prow['paired_ttest_p'] >= 0.001 else "$<0.001$"
            p_w = f"{prow['wilcoxon_p']:.4f}" if prow['wilcoxon_p'] >= 0.001 else "$<0.001$"
            lines.append(f"    {comp_name} & {d_mean} & {d_ci} & {p_t} & {p_w} \\\\")
        lines.extend([
            r"    \hline",
            r"  \end{tabular}",
        ])

    lines.append(r"\end{table}")
    return "\n".join(lines)


def _generate_markdown_report(
    title: str,
    stats_df: pd.DataFrame,
    paired_results: List[Dict[str, Any]],
    caution_note: str,
) -> str:
    md = [f"# {title}\n"]
    md.append("## Summary Statistics per Arm\n")
    md.append("| Experimental Arm | Folds | Mean Dice | Std Dev | SEM | 95% CI | Median | IQR | Min | Max |")
    md.append("|:---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|")

    for _, r in stats_df.iterrows():
        md.append(
            f"| {r['label']} | {int(r['n_folds'])} | {r['mean']:.4f} | {r['std']:.4f} | {r['sem']:.4f} | "
            f"[{r['ci95_low']:.4f}, {r['ci95_high']:.4f}] | {r['median']:.4f} | {r['iqr']:.4f} | "
            f"{r['min']:.4f} | {r['max']:.4f} |"
        )

    if paired_results:
        md.append("\n## Paired Hypothesis Statistical Tests\n")
        md.append("| Comparison (B vs A) | N Folds | Mean $\\Delta$ (B - A) | Std $\\Delta$ | 95% CI ($\\Delta$) | Cohen's $d_z$ | Wins (B > A) | Losses | Paired $t$-test $p$ | Wilcoxon $p$ |")
        md.append("|:---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|")
        for p in paired_results:
            p_t_fmt = f"{p['paired_ttest_p']:.4f}" if p['paired_ttest_p'] >= 0.001 else "<0.001"
            p_w_fmt = f"{p['wilcoxon_p']:.4f}" if p['wilcoxon_p'] >= 0.001 else "<0.001"
            comp_display = p.get("comparison", f"{p['arm_b']} vs {p['arm_a']}")
            md.append(
                f"| {comp_display} | {p['n_folds']} | {p['mean_diff']:+.4f} | {p['std_diff']:.4f} | "
                f"[{p['ci95_low']:+.4f}, {p['ci95_high']:+.4f}] | {p['cohens_d']:+.3f} | "
                f"{p['wins_b']} ({p['win_rate_b']:.1f}%) | {p['losses_b']} | {p_t_fmt} | {p_w_fmt} |"
            )

    md.append(f"\n> **Note:** {caution_note}\n")
    return "\n".join(md)


def main() -> None:
    args = parse_args()
    fold_results_path = resolve_path(args.fold_results)
    if fold_results_path.is_dir():
        fold_results_path = fold_results_path / "fold_results.csv"

    if not fold_results_path.exists():
        raise FileNotFoundError(f"Fold results file not found at: {fold_results_path}")

    df = pd.read_csv(fold_results_path)
    output_dir = resolve_path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    configs_dir = resolve_path(args.configs_dir) if args.configs_dir else None
    if configs_dir is None and (fold_results_path.parent / "configs").exists():
        configs_dir = fold_results_path.parent / "configs"

    preset = _infer_hypothesis_preset(str(fold_results_path), args.hypothesis)
    custom_map = _parse_custom_label_map(args.label_map)

    # Assign formal labels
    df["label"] = df["arm"].apply(lambda a: _resolve_arm_label(a, configs_dir, custom_map))

    pairs_to_evaluate = list(args.pairs)
    available_arms = list(df["arm"].unique())

    default_title = "Cross-Validation Segmentation Results"
    if preset == "h1":
        default_title = "Hypothesis 1: Single-Phase Baseline vs Multiphase Training (PV Evaluation)"
        if not pairs_to_evaluate and "baseline_single_phase" in available_arms and "multiphase_train_single_infer" in available_arms:
            pairs_to_evaluate.append("baseline_single_phase:multiphase_train_single_infer")
    elif preset == "h2":
        default_title = "Hypothesis 2: Impact of Multiphase CT Registration on Segmentation"
        if not pairs_to_evaluate and "baseline_unregistered" in available_arms and "registered_training" in available_arms:
            pairs_to_evaluate.append("baseline_unregistered:registered_training")
    elif preset == "h4":
        default_title = "Hypothesis 4: Multiphase Benefit Across Encoder Capacities"
        if not pairs_to_evaluate:
            if "small_single_phase" in available_arms and "small_multiphase" in available_arms:
                pairs_to_evaluate.append("small_single_phase:small_multiphase")
            if "large_single_phase" in available_arms and "large_multiphase" in available_arms:
                pairs_to_evaluate.append("large_single_phase:large_multiphase")

    title = args.title or default_title

    # Determine arm ordering
    if args.order:
        ordered_arms = [a for a in args.order if a in available_arms]
    else:
        preferred_order = [
            "baseline_single_phase",
            "multiphase_train_single_infer",
            "baseline_unregistered",
            "registered_training",
            "small_single_phase",
            "small_multiphase",
            "large_single_phase",
            "large_multiphase",
        ]
        ordered_arms = [a for a in preferred_order if a in available_arms]
        for a in available_arms:
            if a not in ordered_arms:
                ordered_arms.append(a)

    arm_labels = [_resolve_arm_label(a, configs_dir, custom_map) for a in ordered_arms]

    # Compute descriptive stats
    stats_df = _compute_descriptive_stats(df, args.dice_column)
    stats_df["sort_order"] = stats_df["arm"].apply(lambda a: ordered_arms.index(a) if a in ordered_arms else 999)
    stats_df = stats_df.sort_values("sort_order").drop(columns=["sort_order"])
    stats_df.to_csv(output_dir / "summary_stats.csv", index=False)

    # Compute paired test statistics
    paired_rows = []
    for pair_str in pairs_to_evaluate:
        arm_a, arm_b = [p.strip() for p in pair_str.split(":", 1)]
        if arm_a in available_arms and arm_b in available_arms:
            lbl_a = _resolve_arm_label(arm_a, configs_dir, custom_map)
            lbl_b = _resolve_arm_label(arm_b, configs_dir, custom_map)
            paired_rows.append(_compute_paired_stats(df, arm_a, arm_b, lbl_a, lbl_b, args.dice_column))
    paired_df = pd.DataFrame(paired_rows) if paired_rows else None
    if paired_df is not None and not paired_df.empty:
        paired_df.to_csv(output_dir / "paired_tests.csv", index=False)

    # Generate publication boxplot
    png_path = output_dir / "dice_boxplot.png"
    pdf_path = output_dir / "dice_boxplot.pdf"
    _plot_formal_boxplot(
        df=df,
        dice_col=args.dice_column,
        ordered_arms=ordered_arms,
        arm_labels=arm_labels,
        title=title,
        output_png=png_path,
        output_pdf=pdf_path,
        paired_results=paired_rows,
        dpi=args.dpi,
    )

    # Generate Markdown and LaTeX reports
    md_report = _generate_markdown_report(title, stats_df, paired_rows, CAUTION_NOTE)
    (output_dir / "summary_report.md").write_text(md_report, encoding="utf-8")

    tex_table = _generate_latex_table(stats_df, paired_df, caption=title, label=f"tab:{preset}_results")
    (output_dir / "table_latex.tex").write_text(tex_table, encoding="utf-8")

    # Optional copy to thesis image folder
    if args.copy_to_thesis_img:
        thesis_dest = resolve_path(args.copy_to_thesis_img)
        thesis_dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(png_path, thesis_dest)
        if thesis_dest.suffix.lower() == ".png":
            pdf_dest = thesis_dest.with_suffix(".pdf")
            shutil.copy2(pdf_path, pdf_dest)
        print(f"Copied figure to thesis: {thesis_dest}")

    print(f"\n[OK] Successfully aggregated results for: {title}")
    print(f"  - Summary Stats:    {output_dir / 'summary_stats.csv'}")
    if paired_df is not None:
        print(f"  - Paired Tests:     {output_dir / 'paired_tests.csv'}")
    print(f"  - Markdown Report:  {output_dir / 'summary_report.md'}")
    print(f"  - LaTeX Table:      {output_dir / 'table_latex.tex'}")
    print(f"  - Boxplot Figure:   {png_path} & {pdf_path}")


if __name__ == "__main__":
    main()
